version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: seek-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seek_admin_db
      MYSQL_USER: seek_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - seek-network

  # Spring Boot App
  app:
    build: .
    container_name: seek-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/seek_admin_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: seek_user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mysql
    networks:
      - seek-network

  # Loki - Log aggregation
  loki:
    image: grafana/loki:2.9.0
    container_name: seek-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - seek-network

  # Promtail - Log shipper
  promtail:
    image: grafana/promtail:2.9.0
    container_name: seek-promtail
    volumes:
      - ./logs:/var/log/app:ro
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - seek-network
    depends_on:
      - loki

  # Prometheus - Metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: seek-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - seek-network

  # Grafana - Log visualization
  grafana:
    image: grafana/grafana:10.2.0
    container_name: seek-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - seek-network
    depends_on:
      - loki
      - prometheus

volumes:
  mysql_data:
  grafana_data:

networks:
  seek-network:
    driver: bridge
