# Prometheus configuration for Seek Management App
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Actuator metrics
  - job_name: 'seek-management-app'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # MySQL Exporter (optional - if you want DB metrics)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
