{
 "title": "Seek Management - Logs Dashboard",
 "tags": [
  "logs",
  "seek-management"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"seek-management-app\"} |= \"INFO\""
    }
   ]
  },
  {
   "title": "Warn Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"seek-management-app\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"seek-management-app\"} |= \"ERROR\""
    }
   ]
  }
 ]
}